# Foreman â€” Roblox toolchain manager
# Install: cargo install foreman (or download from https://github.com/Roblox/foreman)
# Usage:  foreman install

[tools]
rojo = { github = "rojo-rbx/rojo", version = "=7.4.4" }
wally = { github = "UpliftGames/wally", version = "=0.3.2" }
selene = { github = "Kampfkarren/selene", version = "=0.27.1" }
stylua = { github = "JohnnyMorganz/StyLua", version = "=2.0.2" }
wally-package-types = { github = "JohnnyMorganz/wally-package-types", version = "=1.3.2" }
