[package]
name = "thebardchat/angel-cloud-roblox"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"
description = "Angel Cloud ROBLOX â€” The Cloud Climb"

[dependencies]
Knit = "sleitnick/knit@1.6.0"
Promise = "evaera/promise@4.0.0"
Signal = "stravant/goodsignal@0.2.0"
Trove = "sleitnick/trove@1.1.0"
TableUtil = "sleitnick/table-util@1.2.0"
Timer = "sleitnick/timer@1.1.0"

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"

[place]
shared-packages = "Packages"
server-packages = "ServerPackages"
